tasks:
  - before: |
      echo 'export CARGO_HOME="/home/gitpod/.cargo"' >> ~/.bashrc
      source ~/.bashrc
    init: |
      gp open contract/src/lib.rs

vscode:
  extensions:
    - matklad.rust-analyzer
