[package]
name = "gear-feeds-channel"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2021"

[dependencies]
circular_buffer = {git = "https://github.com/breathx/circular-buffer-rs.git", default-features = false }
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive", "full"] }
gstd = {git = "https://github.com/gear-tech/gear.git", features = ["debug"] }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"]}
scale-info = { version = "2.0.1", default-features = false, features = ["derive"] }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git"}

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git" }
