name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Artifact cache
        uses: Swatinem/rust-cache@v1

      - name: Prepare
        run: make prepare

      - name: Build
        run: make
